<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="HamsterWheel.CodeShare.Common" PrivateAssets="All" />
      <PackageReference Include="HamsterWheel.HLinq"/>
      <PackageReference Include="HamsterWheel.HLinq.Abstractions" />
      <PackageReference Include="HamsterWheel.HLinq.AspNet" />
    </ItemGroup>

</Project>
